### ISSUE TITLE
patch vs increment

### ISSUE THREAD

**Issue by datapolitical** [PaulHatch/semantic-version#15]
At the moment my version updates in increments (2.1.0+1) for every push, and updates major (3.0.0) and minor (2.2.0) when specified in the commit. But how do I get it to update at the patch level (2.1.1) instead of just incrementing? I've read the docs a few times and I'm not sure.

**Comment by PaulHatch** [comment]
Patch is the default value incremented when the commits in question do not contain either a major or minor trigger.

Generally the process works like this (assuming _bump each commit_ is false):

- Determine the range of commits to be evaluated, e.g. all the commits since the most recent version tag
- Check if any of these have a commit message with a "major" indicator, if so this is a major version change
- Check if any of these have a commit message with a "minor" indicator, if so this is a minor version change
- Otherwise this is a patch version change

Major changes increment the major version by one and set the minor and patch to zero.
Minor changes increment the minor version by one and sets the patch to zero
Patch change increment the patch by one.

In all these cases the increment value will be the number of subsequent commits since the last change, in other words the number of times the version has remained the same.

**Comment by datapolitical** [comment]
So my pushes to GitHub aren’t incrementing the patch level for some reason.

**Comment by PaulHatch** [comment]
They will only increment on the commit after a version tag (unless you have the bump every commit option turned on).

Note that all the implicit versions (which is what the action generates) are the same here after the tag:

![Commits Graph](https://raw.githubusercontent.com/PaulHatch/semantic-version/master/versioning.drawio.svg?raw=true)

Once you tag a commit, the next version will be incremented.

**Comment by datapolitical** [comment]
So it turns out that it was an ordering issue. The version step had to come after build and deploy.

Also, your images don’t work on dark mode.
![D506FDF7-3F48-48A2-A6EB-6148DE65FC8F](https://user-images.githubusercontent.com/696957/103238460-aa8a9000-48ff-11eb-8221-373dfbdc7bdc.png)
