### ISSUE TITLE
Problem counting minor versions without a tag

### ISSUE THREAD

**Issue by DouglasAR01** [PaulHatch/semantic-version#23]
Hello.
I'm using your awesome Github Action in a new project and I'm not sure if I'm facing a problem. 
I haven't tagged any commit yet because the project is still very new, however I'm using the semantic version minor_pattern to keep track of the minor updates. The next image shows the commit history and some notes of the version history as it should be:
![image](https://user-images.githubusercontent.com/33143337/107802559-7e9c6000-6d2f-11eb-9c29-e87c0c54f13e.png)
The problem is that I checked at the last commit, "(MINOR) Configurable role gates",  jobs results in order to see if everything is going fine. I encountered this:
![image](https://user-images.githubusercontent.com/33143337/107803088-2580fc00-6d30-11eb-862a-716034c6dcf4.png)
I'm not sure if the problem reason is because I haven't tagged any commit yet or if it is an expected behavior or if I'm missing something.
Thank you!

**Comment by PaulHatch** [comment]
Right, this is expected behavior. The version only increments once per version, regardless of how many commits match the pattern.

When the action runs it looks at all the commits from the target commit back to either the last tag, or the initial commit if no tags are present (that's what triggers that warning). These commit messages are evaluated to determine the _type_ of change the next version should use.

If any commit messages in this range match the `major_pattern`, this is considered a major version.
Otherwise if any match `minor_pattern`, this is considered a minor version.
Otherwise this is considered a patch version.

The version only increments for commits after a version tag (unless `bump_each_commit` is set to true, in which case every commit will be an increment).

**Comment by DouglasAR01** [comment]
Okay, thank you!
