### ISSUE TITLE
[Feature Request] Output previous version

### ISSUE THREAD

**Issue by john681611** [PaulHatch/semantic-version#37]
Would be really nice if the previous version used to calculate the next new version was exposed as a output

**Comment by PaulHatch** [comment]
Hey John, yes I think this is ok. My only concern here is that this version would be confusing. It already seems to confuse people a bit that the version provided is being "predicted"/generated rather than simply extracted, having this value might lead to additional confusion over which one to use. Could you share your use case for this value? Might help with documentation to provide an example.

**Comment by john681611** [comment]
We generate comparison links and therefore you need a previous tag to create the link. We also use it to pull commits for a changelog

**Comment by PaulHatch** [comment]
OK, this fits in with another planned feature, which is including the list of commit authors for a release. All these fields will all be grouped together as "release metadata".

**Comment by PaulHatch** [comment]
This is available in version [v5.0.0](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-alpha)

**Comment by PaulHatch** [comment]
Hey @dtcMLOps, should be in there under the `previous_version` output, unless I misunderstand what you're saying.

Here is the relevant line in the distribution code of v5.0.0-beta:
https://github.com/PaulHatch/semantic-version/blob/v5.0.0-beta/dist/index.js#L404

**Comment by PaulHatch** [comment]
OK, I think I see the issue--I assume here that you are running on a commit that is itself already directly tagged with the version, when this happens the action short-circuits some prediction lookups and does not obtain the previous version.

I've opened a bug ticket, #73, for this.

**Comment by PaulHatch** [comment]
A fix for #73 is available in [v5.0.0-beta2](https://github.com/PaulHatch/semantic-version/releases/tag/v5.0.0-beta2)
