### ISSUE TITLE
[Feature Request] Allow optional Patch as designated term

### ISSUE THREAD

**Issue by CFarley-HYLA** [PaulHatch/semantic-version#43]
It would be nice to be able to use a term to indicate a patch as well as the major/minor commit names  to allow for auto-incrementing without needing to add tags

**Comment by PaulHatch** [comment]
Yes, the plan for v5 of this action is to split out the logic out from the Git interfaces, this will allow pluggable "strategies" that can contain different logic for obtaining information from the repo. In this case a "comment" strategy could be added to the action and used in place of a "tag" strategy which would implement the current behavior.

**Comment by yannduran** [comment]
I've just been looking at you action, hoping to be able to use it instead of `GitVersion`. It's not clear for me from the README how the patch portion of the version currently gets incremented.

I was just about to add an issue when I saw this one, so I hope you both don't mind me piggybacking my question here. You don't have discussion enabled or I would have asked the quest there. TIA

**Comment by PaulHatch** [comment]
Sure, so tl;dr, "patch" is the default if neither major nor minor changes exist in a version context.

The "fundamental theory" here is that you don't know at the time a commit is made whether or not that commit is going to be a release. Maybe you find a bug or you or someone else finds a change after. A consequence of this is that it is not possible to (reliably) put the version information into the repo. Still you may want to use this version during the build, to inject into or name the build artifacts.

This semantic version action then treats each commit in the entire chain of commits since the last commit as the "potentially next release". That release will be a "patch" by default. If in that set of commits, a breaking change exists, the next version is a "major" change, if no major changes exists, but a "minor" change exists (a feature was added), the next version is considered a "minor" type, and finally if neither major nor minor types exist, then "patch" is the default.

Once a change type is determined, the previous version is looked up and incremented by 1 using the appropriate strategy for the release type. This version, the output from this action, is "floating" until a version tag is added (presumably during the actual release), starting a new version. The commit immediately following that release commit will again be incremented by 1.

Additionally, an `increment` output is not part of the semantic version's major/minor/patch values and simply counts the number of commits for this version, starting at 0, and can be used as part of the label portion of the tag to differentiate between pre-release builds.

As of today, in version 4:

- Major and minor changes are detected by searching the commit messages for the appropriate pattern (`(MAJOR)` and `(MINOR)` by default). The idea here is that while you don't know if the commit will be released, you should know if you made a breaking change or added a feature to the API as defined by server
- The last commit is detected by looking for the last tag matching the tag pattern (semantic version prefixed by `v` by default)
- The last version is detected by parsing the last version tag

The plan for version 5, which I will probably start soon, is to make the code that retrieves the information above modular and to provide a few pluggable options to define how this data is obtained. This would allow things like using the existence of a release branch to be used to detect the last version.

**Comment by yannduran** [comment]
Thanks Paul. That was very comprehensive. I'm just starting out setting up automated CI/CD.

> Sure, so tl;dr, "patch" is the default if neither major nor minor changes exist in a version context.

I actually don't want the patch version to increment every time I push a commit (or commits), that should be what the `increment` value should represent, in my mind.

Here's what I'm trying to do.

| Action |  Result |
| --------------- | -------- |
| push to master  | build, but no deployment
| push to develop | build, AND a development deployment (ex v1.0.1+pre001, +pre002 etc)
| push a non-standard tag | nothing happens
| push a _correct_ tag (ie v*) | build AND a production deployment (ex v1.0.1)

The main part that I'm having trouble getting my head around is that a semantic version should only have its patch portion incremented if it represents a backwards compatible bug fix, no? I don't want every commit that I decide to push while working on a bug fix or feature to increment it, only when I've completed the bug fix or feature. 

To have it increment for every pushed commit means it not really a valid semantic version (in my mind) because it's being incremented based on commits and not bug fixes. Otherwise why do we have the build metadata if both it and the patch portion are both being incremented on each push. That sound like what `bump_each_commit=true` would do.

Does that make sense? I'm probably missing something obvious. Am I able to do what I've described with your action?

**Comment by yannduran** [comment]
Thanks Paul! I think that makes it clear for me now. I appreciate the time you've spent explaining it to me.
