### ISSUE TITLE
[Feature Request] Allow to define major, minor, patch instead of searching

### ISSUE THREAD

**Issue by technicallyjosh** [PaulHatch/semantic-version#50]
It would be awesome to have a way to specify a bump based on a value passed in instead of searching the commit message or body. 

The use case is that sometimes failures and other things require manual pushing after the fact. It would be great to use the same workflows but be able to say "give me the next minor version" without commits being involved.

**Comment by PaulHatch** [comment]
Hi Josh,
I guess I'm not entirely clear on what the request is here. The scenario you're describing is the exact purpose of this action; the version is predicted in advance but not actually set until "publish" time, which as of version 5 can come from either a tag or branch. That action marks the target commit as "the commit" for the version and causes the predicted version for any subsequent commits to return the next version. You can override this at any point as well by placing an arbitrary tag/branch and the action will use that version instead.

If this were to be done "without any commits being involved" as you say I'm not sure where the version is actually coming from...? If you just mean the commit type that currently comes from the commit message, this can be customized by providing a new [`VersionClassifier`](https://github.com/PaulHatch/semantic-version/blob/master/src/providers/VersionClassifier.ts) implementation.

There are several other interfaces which can similarly be used to plug in new behavior--for this repo the core is only ever going to support getting information from the Git repo itself, but version 5 is a rewrite specifically designed to make forking and extending for custom scenarios easier. I am planning to add documentation on extending soon.

**Comment by technicallyjosh** [comment]
Hey there,

Sorry If I wasn't clear.

For example, we have actions that you can trigger manually and bump the version aside from git commits/pushes. During this manual bump, you specify as an argument major, minor, or patch. As far as I could tell from the docs, it must determine major, minor, patch from the commit message or body. 

I do understand and can appreciate that that the goal of the package is to not have to have human interaction with it for versioning, but figured it would be nice to have something similar to what I'm asking so we don't have to go to other actions for these manual flows.

**Comment by PaulHatch** [comment]
Yeah, so that's a bit too specific and conflicts with two goals for this action:

> - Derive the version only from the git repository itself
> - Do not require the version to be maintained by hand

If you want this I'd recommend creating a fork. You could add this behavior by adding an input field to the `ActionConfig` class (also update the main.ts file to assigns the new property), and either create a new `VersionClassifier` or update the `DefaultVersionClassifier` to use this value. There's a method called `resolveCommitType` that could be modified fairly easily to simply provide the input value instead of searching the commits. There are a few other parameters that won't make sense with this, such as the count of commits which have this version. Since you'l be injecting the command type on demand the action will not be able to determine this. You may find it is not an issue for you depending on what information you are using from the output.

**Comment by technicallyjosh** [comment]
Sounds good. Thanks for taking the time!
