### ISSUE TITLE
Merging 2 PR at same time with semantic version returns same version

### ISSUE THREAD

**Issue by Guriqbal-Singh-Alida** [PaulHatch/semantic-version#51]
Scenario: Merge 2 PRs, 1 right after another.  1 of the action runs and other one is waiting(by using concurrency: ${{ github.workflow }})
After 1st PR processing done it create new tag and pushes it but the when second PR runs after, it fails to pick up newly created tag returns the same old tag.

currently using v4.0.3 for action.
Any help is appreciated

**Comment by andyfcx** [comment]
I have this problem too, version does not increase

**Comment by PaulHatch** [comment]
So this action is going to be running entirely on the local copy of the repo, so any concurrency issues will need to be handled higher in the "stack". Having said that, normally this kind of concern would not be an issue since the intended use case/concept for this action is that the release is being created in a manual process (e.g. after a release passes QA, etc.), as opposed to automatically created tags. There is an option to increment each commit automatically that better supports this kind of process (each commit is a new version) and it would not require tags at all, though not sure when your repo is being pulled so this may or may not help.

If you can't lock this down and the conflict is in the "increment" portion of the version you might consider using the Git hash as the version tag suffix instead.
