### ISSUE TITLE
[Question] What `branch` and `use_branches` are used for?

### ISSUE THREAD

**Issue by gumaciel** [PaulHatch/semantic-version#80]
I needed it to detect a change in the version of a given branch, are these inputs for that? I can't use it, whenever I use the version stays 0.0.0

https://github.com/Poing-Studios/godot-admob-editor/actions/runs/3809020305

**Comment by PaulHatch** [comment]
Hey @gumaciel,
`use_branches` tells the action to use branches instead of tags to locate the commit of the most recent version and determine the version number. It is recommend to use tag instead unless of branches unless you need to support ongoing releases for multiple version concurrently.

`branch` is merely for overriding the branch to look at, it is set to HEAD by default and most projects will not need to change this.

This action does provide a "changed" output, which intended for determining whether a change occurred in a service in a mono-repo setup which is using `change_path`. This could be used for example to short-circuit running builds for services which did not change. It will always be true if no change path was specified.

**Comment by gumaciel** [comment]
~Ty bro, your Action is the best ❤️
