### ISSUE TITLE
Specify pre-release format without interfering with interfering with regular releases

### ISSUE THREAD

**Issue by Kantis** [PaulHatch/semantic-version#93]
Hi!

I'm trying to specify my pre-release format to `version_format: "${major}.${minor}.${patch}.${increment}-SNAPSHOT"`, but for stable versions (e.g. tagged ones) I would still like to have just `${major}.${minor}.${patch}`. It seems to me that the version-format is _always_ applied. Is there any way to work around this? Or could a `prerelease_version_format` configuration option be added?

**Comment by PaulHatch** [comment]
I'd recommend just using the component outputs directly:

```

env:
  VERSION: ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
  PRERELEASE_VERSION: ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}-PRE${{ steps.version.outputs.increment }}
```
or you can use the version output and append the increment:
```
VERSION: ${{ steps.version.outputs.version }}
PRERELEASE_VERSION: ${{ steps.version.outputs.version }}-PRE${{ steps.version.outputs.increment }}
```

This is also frequently important because support for the increment value is not very well standardized. For example [Docker tags do not support `+` characters](https://github.com/distribution/distribution/issues/1201) which is commonly used for semver labels, while .NET assemblies have long used a format like `#.#.#.#`. As a result you often end up needing to create multiple formatted versions so adding a "prerelease" format would just be one of several tag types required.

If I could go back and start over I'd remove the formatted version from the action I think I would, because as this ticket illustrates, version formatting is really beyond the scope of this action.

**Comment by Kantis** [comment]
How do you decide whether the GH workflow should use the `VERSION` or `PRERELEASE_VERSION`?

**Comment by PaulHatch** [comment]
Well that is very much up to your build, this was just to illustrate both methods of obtaining the version string. Most of my builds have a master and release branch with a completely different build for each (so I actually just have a single `VERSION` variable with two different ways of setting it). That's very simple but not always ideal especially if your build is more complicated because there are two copies being maintained. You might be reusing the build with conditionals, promoting immutable binaries, etc. and each of these would probably answer that question differently.

I would not hold this up as a model build, it's quite old now and doesn't make use of some new features that have been added to GitHub Actions since, and has a few other issues besides, but [here is one example from another project](https://github.com/PaulHatch/trancesql/tree/master/.github/workflows).

There are two pipelines here, a buld.yaml and release.yaml. The build runs on master:
```
on:
  push:
    branches:
      - master
```
And release pushes the packages to NuGet on release, only when published:
```
on:
  release:
    types: [published]
```

You can see they are using two different formats.

**Comment by Kantis** [comment]
Thanks for the elaborate response. 

I am using some conditionals. My reasoning was that "every commit to main" should be a pre-release or a release version.  

```mermaid
stateDiagram-v2
  state "workflows/build-and-test.yaml" as build
  state "workflows/publish.yaml" as publish
  state "[push on main]" as push
  state "[tag pushed]" as release
    [workflow_dispatch] --> build
    push --> build
    release --> build
    build --> publish
```
Both the build and publish steps are quite complicated. We use matrices to build for multiple targets (mac, linux, windows, 
ios, etc). ([The project](https://github.com/Kantis/ks3) is open-source, in case you want to poke around :smiley:)

I thought it would be easier if the `publish` step could determine the release-type itself, otherwise I imagine I'd have to do something like this. `build` and `publish` would both have to be changed to accept the version as input all the way

```mermaid
stateDiagram-v2
  state "workflows/build-and-test.yaml" as build
  state "Calculate release version" as vrelease
  state "Calculate pre-release version" as vprerelease
  state "workflows/publish.yaml" as publish
  state "[push on main]" as push
  state "[tag pushed]" as release
  state "[workflow_dispatch" as dispatch
  note left of dispatch: Manually input version and ref
    dispatch --> build
    push --> vprerelease
    release --> vrelease
   vrelease --> build
  vprerelease --> build
    build --> publish
```

It felt like an easier solution to stick to the first setup, if we could just derive whether it's a release or pre-release based on the presence/absence of a tag. I made a [PR draft](https://github.com/PaulHatch/semantic-version/pull/94) with what I had in mind. In my workflow I could use the additional output to select whether I want to use `${major}.${minor}.${patch}` or `${major}.${minor}.${patch}-prerelease.${increment}`
