### ISSUE TITLE
I can't seem to only get the increment version part to increase

### ISSUE THREAD

**Issue by WillooWisp** [PaulHatch/semantic-version#99]
I have a version format like this:
"${major}.${minor}.${patch}-16-${increment}"

I have a tag like this:
v3.0.2

Now I only want each build to increase the increment part like so...
3.0.2-16-1
3.0.2-16-2
3.0.2-16-3

But I got a version like this
3.0.3-16-3 where both patch and increment was increased. 

Is my use cases supported or am I doing something wrong?

**Comment by nikolajskov** [comment]
Hi @WillooWisp,

The _increment_ is the number of commits for the current version, so it doesn't change if there are no new commits. Also, if the version changes, the increment is restarted from zero. A version like _3.0.3-16-3_ indicates three commits for version 3.0.3 since the previous version (3.0.2). If no commits with _(MAJOR)_ or _(MINOR)_ changes are detected, the _patch_ number is incremented.

What you're looking for sounds like a _build number_ from your build system. E.g. GitHub has a _GITHUB_RUN_NUMBER_ which is the number of runs for a particular workflow. It is incremented for each new run.

Hope it helps :-)
